version: "2"
run:
  go: "1.24"
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - dupl
    - goconst
    - gocritic
    - misspell
    - mnd
    - unconvert
    - unparam
  disable:
    - depguard
    - gocyclo
    - gosec
  settings:
    dupl:
      threshold: 120
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (*os.File).Close
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    goconst:
      min-len: 3
      min-occurrences: 5
    gocritic:
      disabled-checks:
        - regexpMust
        - rangeValCopy
        - appendAssign
        - hugeParam
      enabled-tags:
        - performance
      disabled-tags:
        - experimental
    nakedret:
      max-func-lines: 20
    staticcheck:
      checks:
        - all
        - -SA9005
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
